name: MoeCore
main: co.mcsky.moecore.MoeCore
version: ${version}
api-version: 1.13
author: Nailm
website: https://mimaru.me
depend: [ helper ]
softdepend: [ Vault, LuckPerms, NyaaCore, Towny ]
loadbefore: [ NyaaUtils ]